### PR TITLE
Issue21 sourmash version

### PR DESCRIPTION
**Pull request by chunyuma**
Hi @dkoslicki,

I have rewritten most of YAML code in order to make it run faster with less RAM. However, the RAM usage still depends on the scale and number of genomes in the training data.

According to a test based on ~30K genomes with `scale=100` and `kmer=31` (including fungi, viruses, bacteria, archaea) mainly collected from Refseq and Genbank (the size of .zip database is ~16G), the whole running time (including training and YACHT) is ~2 hours. It should be faster with gtdb-rep database. For the RAM usage, I have tried multiple methods (e.g., divide-and-conquer) to reduce RAM but it still needs ~150GB. The part that consumes the most RAM is [this](https://github.com/KoslickiLab/YACHT/blob/a3b094bc6c9f288c50e95c5b2bbbee3f9b96eefc/srcs/hypothesis_recovery_src.py#L66-L138) function.

### CODE REVIEW

**Comment by mfl15** [comment]
@chunyuma we need to fix a pipeline 
image

**Comment by chunyuma** [comment]
Hi @mfl15, I renamed the YAML file to `yacht_env.yml`. Could you please change the pipeline to adpot to this new name? Or I can change its name back if you like.

**Comment by mfl15** [comment]
@chunyuma I guess we need to add sourmash scripts multisearch to readme as we are using it now. Also we need to add it to pipeline.

**Comment by dkoslicki** [comment]
@mfl15 I think the plan is that @chunyuma is going to do a bit of A/B testing on speed and RAM usage (and file space) for the old/matrix-based approach, and this new approach that uses branchwater. After we take a look at that, we'll consider if we want to make this new approach the main thing, or just leave it as an optional, experimental method.

**Comment by mfl15** [comment]
ok sure, @chunyuma please ping me when it is ready so I will update the pipeline FYI @dkoslicki

**Pull request merged**
