### PR TITLE
Accelerate `yacht train`

### PR DESCRIPTION
**Pull request by chunyuma**
This PR is created to integrate [Mahmudur's new algorithm](https://github.com/mahmudhera/accelarated_sketch_comparison/blob/main/compute_by_all_hashes.cpp) and [post-processing method](https://github.com/mahmudhera/accelarated_sketch_comparison/blob/main/post_process.cpp) written with cpp script to accelerate `yacht train`

We need to do the following tasks:

- [x] add the cpp scripts into the branch (under ./yacht/cpp_scripts) @mahmudhera.
- [x] modify related scripts for integrating these cpp scripts in YACHT @chunyuma 
- [x] create a makefile and other related scripts for pre-processing @mahmudhera @chunyuma 
- [x] modify some tests @chunyuma 
- [x] integrate into the `main` branch

### CODE REVIEW

**Comment by mahmudhera** [comment]
Hi @chunyuma, as this is now implemented in https://github.com/KoslickiLab/fast_yacht_train/pull/3, do I still need to add the cpp code in the repository? Also, it looks like some code duplication has blocked this PR. What are your plans on this? Do you want me to take some things off your plate?

**Comment by chunyuma** [comment]
No worries @mahmudhera. I can handle the rest. I have added your cpp scripts to YACHT and they looks good. I just need a few more tests.

**Comment by mahmudhera** [comment]
Excellent, LMK if I can help.

**Comment by mahmudhera** [comment]
Hello @chunyuma I see some tests blocking the merge. Do you want me to work on any of these?

**Comment by chunyuma** [comment]
Thank @mahmudhera, it is not a block but the merging needs at least 1 approving review. The code has passed all tests now. But there are some problems about `conda install` I need to figure out before merging. I will let you know when it is done.

**Review by mahmudhera — COMMENTED** [review]
LGTM, but cautiously waiting for @dkoslicki to approve.

**Review by dkoslicki — APPROVED** [review]
From what I can see, this looks good to me. @chunyuma LMK when the conda issue is resolved and you or I can merge this in

**Review by mahmudhera — DISMISSED** [review]

**Review by mahmudhera — APPROVED** [review]

**Review by mahmudhera — APPROVED** [review]

**Pull request merged**
